name: torrent_model
description: A Dart library for parsing .torrent file to Torrent model/saving Torrent model to .torrent file.
version: 1.0.3
repository: https://github.com/eclipseglory/torrent_model
issue_tracker: https://github.com/eclipseglory/torrent_model/issues
publish_to: https://pub.dev/

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
 crypto: ^3.0.2
 bencode_dart:
   git:
      url: https://github.com/PURUSHOTHAM-REDDY-N/bencode_dart.git
      ref: master 
 path: ^1.8.3

dev_dependencies:
  test: ^1.14.4
